# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_miNEXT3_timesTwo', PACKAGE = 'miNEXT3', x)
}

fk_3 <- function(k1, k2, k3, m1, m2, m3, x1, y1, z1) {
    .Call('_miNEXT3_fk_3', PACKAGE = 'miNEXT3', k1, k2, k3, m1, m2, m3, x1, y1, z1)
}

fk <- function(k1, k2, k3, m1, m2, m3, x1, y1, z1) {
    .Call('_miNEXT3_fk', PACKAGE = 'miNEXT3', k1, k2, k3, m1, m2, m3, x1, y1, z1)
}

D_share <- function(xi, yi, zi, m1, m2, m3, q) {
    .Call('_miNEXT3_D_share', PACKAGE = 'miNEXT3', xi, yi, zi, m1, m2, m3, q)
}

D_share_yhc <- function(xi, yi, zi, m1, m2, m3, q) {
    .Call('_miNEXT3_D_share_yhc', PACKAGE = 'miNEXT3', xi, yi, zi, m1, m2, m3, q)
}

D0_rare_yhc <- function(xi, yi, zi, m1, m2, m3) {
    .Call('_miNEXT3_D0_rare_yhc', PACKAGE = 'miNEXT3', xi, yi, zi, m1, m2, m3)
}

D_q0_in_3 <- function(xi, yi, zi, m1, m2, m3) {
    .Call('_miNEXT3_D_q0_in_3', PACKAGE = 'miNEXT3', xi, yi, zi, m1, m2, m3)
}

q2_p_cpp <- function(x1, y1, z1, m1, m2, m3, n1, n2, n3) {
    .Call('_miNEXT3_q2_p_cpp', PACKAGE = 'miNEXT3', x1, y1, z1, m1, m2, m3, n1, n2, n3)
}

D_q01_in_3 <- function(xi, yi, zi, m1, m2, m3, q) {
    .Call('_miNEXT3_D_q01_in_3', PACKAGE = 'miNEXT3', xi, yi, zi, m1, m2, m3, q)
}

h0_3_1hat_cpp <- function(pi1, pi2, pi3, m1, m2, m3s, n1, n2, n3) {
    .Call('_miNEXT3_h0_3_1hat_cpp', PACKAGE = 'miNEXT3', pi1, pi2, pi3, m1, m2, m3s, n1, n2, n3)
}

h0_3_2hat_cpp <- function(pi1, pi2, pi3, m1, m2s, m3s, n1, n2, n3) {
    .Call('_miNEXT3_h0_3_2hat_cpp', PACKAGE = 'miNEXT3', pi1, pi2, pi3, m1, m2s, m3s, n1, n2, n3)
}

Efk_q1_3 <- function(pi1, pi2, pi3, m1, m2, m3, k1, k2, k3) {
    .Call('_miNEXT3_Efk_q1_3', PACKAGE = 'miNEXT3', pi1, pi2, pi3, m1, m2, m3, k1, k2, k3)
}

h1_3_1cpp <- function(pi1, pi2, pi3, m1, m2, m3, n1, n2, n3) {
    .Call('_miNEXT3_h1_3_1cpp', PACKAGE = 'miNEXT3', pi1, pi2, pi3, m1, m2, m3, n1, n2, n3)
}

h1_3_2cpp <- function(pi1, pi2, pi3, m1, m2, m3, n1, n2, n3) {
    .Call('_miNEXT3_h1_3_2cpp', PACKAGE = 'miNEXT3', pi1, pi2, pi3, m1, m2, m3, n1, n2, n3)
}

h1_3_1hat_cpp <- function(pi1, pi2, pi3, m1, m2, m3, n1, n2, n3) {
    .Call('_miNEXT3_h1_3_1hat_cpp', PACKAGE = 'miNEXT3', pi1, pi2, pi3, m1, m2, m3, n1, n2, n3)
}

h1_3_2hat_cpp <- function(pi1, pi2, pi3, m1, m2, m3, n1, n2, n3) {
    .Call('_miNEXT3_h1_3_2hat_cpp', PACKAGE = 'miNEXT3', pi1, pi2, pi3, m1, m2, m3, n1, n2, n3)
}

rcpp_hello_world <- function() {
    .Call('_miNEXT3_rcpp_hello_world', PACKAGE = 'miNEXT3')
}

